parameters:
#    dla_istudent_welcome.example.class: DlaIstudent\WelcomeBundle\Example

services:
#    dla_istudent_welcome.example:
#        class: %dla_istudent_welcome.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
