<?php

namespace DlaIstudent\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImageActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageActivityRepository extends EntityRepository
{
}
